- hosts: master:nodes
  sudo: true
  tasks:
    - name: install vim
      apt: name=vim state=present

    - name: Generating RSA key for vagrant
      apt: name=vagrant generate_ssh_key=yes  


- hosts: nodes
  sudo: true
  tasks:
    - name: install apache2
      apt: name=apache2 state=present


- hosts: master
  sudo: true
  tasks:
    - name: install python3
      apt: name=python3 state=present

    # - name: Generating RSA key for vagrant
    #   user: name=vagrant generate_ssh_key=yes

    # - name: Downloading pub key
    #   fetch: src=/vagrant/.ssh/id_rsa.pub dest=/tmp/id_rsa.tmp flat=yes

    # - name: Copying local key to 33.33.33.32
    #   local_action: shell cat /tmp/id_rsa.tmp | ssh vagrant@33.33.33.32 "cat >> /vagrant/.ssh/authorized_keys"

    # - name: Coping local key to 33.33.33.33
    #   local_action: shell cat /tmp/id_rsa.tmp | ssh vagrant@33.33.33.33 "cat >> /vagrant/.ssh/authorized_keys"

    # - name: Deleting temporal files
    #   local_action: file  path=/tmp/id_rsa.tmp state=absent

    # - name: Removing temporal keys from 33.33.33.32
    #   shell: ssh vagrant@33.33.33.32  'sed -i "/ansible-generated/d" /vagrant/.ssh/authorized_keys'

    # - name: Removing temporal keys from 33.33.33.33
    #   shell: ssh vagrant@33.33.33.33  'sed -i "/ansible-generated/d" /vagrant/.ssh/authorized_keys'