- hosts: master
  sudo: true
  tasks:
     - name: install vim
       apt: name=vim state=present

- include: jenkins/java_and_jenkins.yml

# - hosts: master:nodes
#   sudo: true
#   tasks:
#     - name: install vim
#       apt: name=vim state=present