- hosts: master:nodes
  sudo: true
  tasks:
    - name: Download wildly.9
      get_url:
        url: http://download.jboss.org/wildfly/9.0.0.Final/servlet/wildfly-servlet-9.0.0.Final.tar.gz
        dest: /wild_src/wildfly-servlet-9.0.0.Final.tar.gz

    - name: Extract Wildfly
      unarchive:
        src: /wild_src/wildfly-servlet-9.0.0.Final.tar.gz
        dest: /opt/

    - name: Add group "wildfly"
      group: 
        name: wildfly

    - name: Add user "wildfly"
      user: 
        name: wildfly 
        group: wildfly 

    - name: Create /domain/log
      file: 
        path: /opt/wildfly-servlet-9.0.0.Final/domain/log
        state: directory
        owner: wildfly

    - name: Create /domain/servers
      file: 
        path: /opt/wildfly-servlet-9.0.0.Final/domain/servers
        state: directory
        owner: wildfly    
    
    - name: Change ownership of Wildlfy installation
      file: 
        path:  /opt/wildfly-servlet-9.0.0.Final/
        owner: wildfly 
        group: wildfly 
        state: directory 
        recurse: yes

    - name: Edit init script
      replace:
        name: /opt/wildfly-servlet-9.0.0.Final/bin/init.d/wildfly-init-debian.sh
        regexp: 'JBOSS_MODE=standalone'
        replace: 'JBOSS_MODE=domain'

    - name: Copy the init script
      copy: 
        src: /opt/wildfly-servlet-9.0.0.Final/bin/init.d/wildfly-init-debian.sh 
        dest: /etc/init.d/wildfly 
        mode: 0755    

    - name: Create symlink
      file: 
        src: /opt/wildfly-servlet-9.0.0.Final 
        dest: /opt/wildfly
        state: link
        force: true

    - name: bck config file
      command: mv /opt/wildfly/domain/configuration/host.xml /opt/wildfly/domain/configuration/host_bck.xml

- hosts: master
  sudo: true
  tasks:
    - name: Copy config file
      copy: 
        src: /config/master/host.xml
        dest: /opt/wildfly/domain/configuration/host.xml 
        mode: 0755

    - name: Add user admin
      lineinfile:
        dest: /opt/wildfly/domain/configuration/mgmt-users.properties
        line: "{{ item.line }}"
      with_items:
        - { line: 'admin=8b719b83947927205e7f4969a4c8514e' }
        - { line: 'slave=8a2a93e7cfefaa1a3ca0d69dfd3e692b' }

- hosts: myserver2
  sudo: true
  tasks:
    - name: Copy config file
      copy: 
        src: /config/slaves/host_one.xml
        dest: /opt/wildfly/domain/configuration/host.xml 
        mode: 0755

- hosts: myserver3
  sudo: true
  tasks:
    - name: Copy config file
      copy: 
        src: /config/slaves/host_two.xml
        dest: /opt/wildfly/domain/configuration/host.xml 
        mode: 0755

- hosts: master:nodes
  sudo: true
  tasks:
    - name: Enable Wildfly to be started at boot
      service: 
        name: wildfly
        enabled: yes 
        state: started
