- hosts: master
  sudo: true
  tasks:
    - name: Download wildly.9
      get_url:
        url: http://download.jboss.org/wildfly/9.0.0.Final/servlet/wildfly-servlet-9.0.0.Final.tar.gz
        dest: /wild_src/wildfly-servlet-9.0.0.Final.tar.gz
    
    # - name: Create /opt/wildfly
    #   file: 
    #     path: /opt/wildfly 
    #     state: directory
    #     owner: root

    - name: Extract Wildfly
      unarchive:
        src: /wild_src/wildfly-servlet-9.0.0.Final.tar.gz
        dest: /opt/

    - name: Add group "wildfly"
      group: 
        name: wildfly

    - name: Add user "wildfly"
      user: 
        name: wildfly 
        group: wildfly 

    - name: Create /domain/log
      file: 
        path: /opt/wildfly-servlet-9.0.0.Final/domain/log
        state: directory
        owner: wildfly

    - name: Create /domain/servers
      file: 
        path: /opt/wildfly-servlet-9.0.0.Final/domain/servers
        state: directory
        owner: wildfly    
    
    - name: Change ownership of Wildlfy installation
      file: 
        path:  /opt/wildfly-servlet-9.0.0.Final/
        owner: wildfly 
        group: wildfly 
        state: directory 
        recurse: yes

    - name: Edit init script
      replace:
        name: /opt/wildfly-servlet-9.0.0.Final/bin/init.d/wildfly-init-debian.sh
        regexp: 'JBOSS_MODE=standalone'
        replace: 'JBOSS_MODE=domain'

#TODO problem with raplace line in config, it should start in domain mode not stanalone

    - name: Copy the init script
      copy: 
        src: /opt/wildfly-servlet-9.0.0.Final/bin/init.d/wildfly-init-debian.sh 
        dest: /etc/init.d/wildfly 
        mode: 0755    

    - name: Create symlink
      file: 
        src: /opt/wildfly-servlet-9.0.0.Final 
        dest: /opt/wildfly
        state: link
        force: true

    - name: bck config file
      command: mv /opt/wildfly/domain/configuration/host.xml /opt/wildfly/domain/configuration/host_bck.xml

    - name: Copy config file
      copy: 
        src: /config/master/host.xml
        dest: /opt/wildfly/domain/configuration/host.xml 
        mode: 0755

    - name: Enable Wildfly to be started at boot
      service: 
        name: wildfly
        enabled: yes 
        state: started