- hosts: master
  sudo: true
  tasks:
    # - name: Download jdk
    #   get_url:
    #     url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    #     dest: /jdk_src/
    #     headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    #     validate_certs: no
    #     timeout: 300

    # - name: Download jre
    #   get_url:
    #     url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jre-8u151-linux-x64.tar.gz
    #     dest: /jre_src/
    #     headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    #     validate_certs: no
    #     timeout: 300        

    - name: Create /opt/jdk
      file: 
        path: /opt/jdk 
        state: directory
        owner: root

    - name: Create /opt/jre
      file: 
        path: /opt/jre 
        state: directory
        owner: root
     
    - name: Extract JDK
      unarchive:
        src: /jdk_src/jdk-8u151-linux-x64.tar.gz
        dest: /opt/jdk

    - name: Extract JRE
      unarchive:
        src: /jre_src/jre-8u151-linux-x64.tar.gz
        dest: /opt/jre

    - name: correct java version selected
      command: 'update-alternatives --install /usr/bin/java java /opt/jre/jre1.8.0_151/bin/java 100'

    - name: correct javac version selected
      command: 'update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_151/bin/javac 100'
