- hosts: master
  sudo: true
  tasks:
    - name: Create /opt/jdk
      file: 
        path: /opt/jdk 
        state: directory
        owner: root

    - name: Create /opt/jre
      file: 
        path: /opt/jre 
        state: directory
        owner: root

    - name: Download JDK
      command: 'wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz -P /opt/jdk/'
     
    - name: Extract JDK
      unarchive:
        src: /opt/jdk/jdk-8u151-linux-x64.tar.gz
        dest: /opt/jdk

    - name: Download JRE
      command: 'wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jre-8u151-linux-x64.tar.gz -P /opt/jre/'
     
    - name: Extract JRE
      unarchive:
        src: /opt/jre/jre-8u151-linux-x64.tar.gz
        dest: /opt/jre

    - name: correct java version selected
      command: 'update-alternatives --install /usr/bin/java java /opt/jre/jre1.8.0_151/bin/java 100'

    - name: correct javac version selected
      command: 'update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_151/bin/javac 100'

    - name: Jenkins - Add key
      apt_key: 
        url: https://pkg.jenkins.io/debian/jenkins.io.key 
        state: present 

    - name: Jenkins - Add repo  
      apt_repository:
        repo: deb http://pkg.jenkins-ci.org/debian-stable binary/
        state: present
        update_cache: yes
      
    - name: Jenkins - Install  
      apt: 
        name: jenkins 
        state: present
        update_cache: yes
