- hosts: master
  sudo: true
  tasks:
    - name: Jenkins - Add key
      apt_key: 
        url: https://pkg.jenkins.io/debian/jenkins.io.key 
        state: present 

    - name: Jenkins - Add repo  
      apt_repository:
        repo: deb http://pkg.jenkins-ci.org/debian-stable binary/
        state: present
        update_cache: yes
      
    - name: Jenkins - Install  
      apt: 
        name: jenkins 
        state: present
        update_cache: yes